esphome:
  name: "lora-sx126x"
  libraries:
     - "SPI"
     - "Ticker"
     - "SX126x-Arduino"

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

external_components:
  - source:
      type: local
      path: esphome/components 
    components: ["lora_sx126x"]

# Enable logging
logger:

wifi:
  networks:
  - ssid: !secret wifi_ssid
    password: !secret wifi_password
  
#ota:
#  password: !secret_ota_password

# Enable Home Assistant API
#api:
#  encryption:
#    key: !secret api_encryption_key

#
web_server:
  port: 80

#spi:
#  clk_pin: GPIO9
#  mosi_pin: GPIO10
#  miso_pin: GPIO11

#i2c:
#  - id: bus_a
#    sda: 17
#    scl: 18

lora_sx126x:
    sensor: "Hello,World"
    
#sensor:
#  platform: lora_sx126x     

#text_sensor:
#  - platform: lora_sx126x
#    name: "LoRa Device Id"
#    id:    devid


