esphome:
  name: "lora-sx126x"
  libraries:
     - "SPI"
     - "Ticker"
     - "SX126x-Arduino"

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

external_components:
  - source:
      type: local
      path: esphome/components 
    components: ["sx126x"]

# Enable logging
logger:

wifi:
  networks:
  - ssid: !secret wifi_ssid
    password: !secret wifi_password
  
ota:
  password: !secret ota_password

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

#
web_server:
  port: 80

#spi:
#  clk_pin: GPIO9
#  mosi_pin: GPIO10
#  miso_pin: GPIO11

#i2c:
#  - id: bus_a
#    sda: 17
#    scl: 18

sx126x:
  name: "LoRa Radio"
  mode: lorawan  # 'lora' or 'lorawan'

# # Interface to radio chip
# pin_lora_reset: 12  # LoRa Reset
# pin-lora_dio_1: 14  # LoRa DIO_1
# pin_lora_busy:  13  # LoRa SPI Busy
# pin_lora_nss:    8  # LoRa SPI CS (Chip Select)
# pin_lora_sclk:   9  # LoRa SPI SCLK
# pin_lora_miso:  11  # LoRa SPI MISO (Master In, Slave Out)
# pin_lora_mosi:  10  # LoRa SPI MOSI (Master Out, Slave In)
# radio_txen:     -1  # LoRa Antenna TX Enable, on some boards.
# radio_rxen:     -1  # LoRa Antenna RX Enable, on some boards.

# --- Use only one of the  LoRa or LoRaWAN set of configuration options ---
# LoRa Specific Options
# Setting these will enable the LoRa radio mode.
  lora:
    rf_frequency: 915000000          # Hz - Manditory
#   tx_output_power: 22              # dBm
#   lora_bandwidth: 0                # [0: 1  25 kHz, 1: 250 kHz, 2: 500 kHz, 3: Reserved]
#   lora_spreading_factor: 7         # [SF7..SF12]
#   lora_codingrate: 1               # [1: 4/5, 2: 4/6,  3: 4/7,  4: 4/8]
#   lora_preamble_length: 8          # Same for Tx and Rx
#   lora_symbol_timeout: 0           # Symbols
#   lora_fx_length_payload_on: -1    # Default: -1 (False)
#   lora_iq_inversion_on: -1         # Default: -1 (False) 
#   rx_timeout_value: 3000           # ms
#   tx_timeout_value: 3000           # ms

# LoRaWAN Specific Oprions
# Setting these will enable the LoRaWAN radio mode
  lorawan:
    region: AU915
#     # AS923
#     # AU915
#     # CN470
#     # CN779
#     # EU433
#     # EU868
#     # IN865
#     # KR920
#     # US915
#     # AS923_2
#     # AS923_3
#     # AS923_4
#     # RU864

    # device_eui: !secret lorawan_device_eui   # 8 bytes
    # The Device EUI is unique to the device, It can be set here, or will be set
    # using the WiFi MAC address, If it is set automatically, then this code
    # won't need to be recompiled for every device.
    
    app_eui: !secret lorawan_app_eui    # 8 bytes     
    # Also referred to as 'join_eui'

    # The following is used for Over The Air Authentication (OTAA)
    app_key:  !secret lorawan_app_key   # 16 bytes

#   # The following is required for Activation By Personalization (ABP) - Untested
#   nwks_key: "00000000000000000000000000000000"  # 16 bytes
#   apps_key: "00000000000000000000000000000000"  # 16 bytes
#   dev_addr: "00000000000000000000000000000000"  # 16 bytes

sensor:
  - platform: sx126x
    id: lorarssi
    name: lorarssi                 # Required for publishing into API and HA 

text_sensor:
  - platform: wifi_info
    ip_address:
      name: ESP IP Address
  - platform: version
    name: "ESPHome Version"
  - platform: template
    name: "Template Text Sensor"
    lambda: |-
      return {"Hello World"};
    update_interval: 60s

  - platform: sx126x
    id: packet_in
    name: packet_in

binary_sensor:
  - platform: gpio
    pin: 5
    id: trigger
    name: "Trigger (In)"
    on_press:
      then:
        - switch.turn_on: monitor_switch    
    on_release:
      then:
        - switch.turn_off: monitor_switch

output:
  - platform: gpio
    pin: 6
    id: monitor
  - platform: gpio
    pin: 35
    id: monitor_led
    
switch:
  - platform: output
    id: monitor_switch
    name: "Monitor Output (Out)"
    output:
#     monitor
      monitor_led


