# This file is an example with a setup for using the SX126X LoRa radio chip.
esphome:
  name: "lora-receiver"
  libraries:
     - "SPI"
     - "Ticker"
     - "SX126x-Arduino"

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

external_components:
  - source:
      type: local
      path: esphome/components 
      #type: git
      #url: github://PaulSchulz/esphome-lora-sx126x
      #ref: main
    components: ["lora_sx126x"]

# Enable logging
logger:
  hardware_uart: "UART0"  # Heltec V3 boards
  
wifi:
  networks:
  - ssid: !secret wifi_ssid
    password: !secret wifi_password
  
ota:
  platform: esphome
  password: !secret ota_password

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

web_server:
  port: 80

# Setup LoRa Radio
lora_sx126x:
  name: "LoRa Radio"
  rf_frequency: 915000000          # Hz - Required

# Report on the received radio signal power
sensor:
  - platform: lora_sx126x
    id: lorarssi
    name: lorarssi                 # Required for publishing into API and HA 

# Read packet data from radio.
text_sensor:
  - platform: lora_sx126x
    id: packet_in
    name: packet_in
