#+TITLE: ESPHome Lora SX126X Component (lora_sx136x)

* Contents :TOC:
- [[#introduction][Introduction]]
  - [[#hardware][Hardware]]
  - [[#testing-and-usage][Testing and Usage]]
- [[#development-comments][Development Comments]]
  - [[#considerations--things-to-fix][Considerations / Things to fix]]
- [[#example-yaml][Example YAML]]

* Introduction
This repository is "Work in Progress"

The aim is to make the LoRa radio, for both LoRa and LoRaWAN, available for use
in ESPHome. In the process, it is hoped that the use of this SX126X can be as
easy as possible and in most cases wholly driven from the ESPHome YAML files.

** Hardware
This component is being developed on the Heltec V3 Development Boards.
Namely:

- Heltec Wifi Lora 32 V3
- Heltec Wireless Lite V3

At the present time, these boards are not available for specifying in the
ESPHome YAML file (when using the Arduino framework). In order to make these
boards work with the available version of ESPHome, the following YAML is required:

#+begin_src yaml
esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino
#+end_src

** Testing and Usage
The files *lora-sx126x.yaml* and *secret.yaml* provide a example of how to use the
integration. To use with a working version of ESPHome, edit *secret.yaml* to add
your local Wifi details, then run:

#+begin_src bash
  esphome run lora-sx126x.yaml
#+end_src

* Development Comments
This esphome component currently does some things which are not encouraged by
the ESPHome Core and Component developers.

It is always hoped that this component will become compliant enough to be
included in ESPHome, but in the meantime, it can be included in your ESPHome
build by either cloning this repository locally and adding an external_component
with a local source; or by including the github repository directly as an
external_component. See the [[https://esphome.io/components/external_components.html][External Components]] documentation.

Local source for external component:
#+begin_src yaml
  external_components:
    - source:
        type: local
        path: esphome/components 
      components: ["lora_sx126x"]
#+end_src

and, Github source for external component
#+begin_src yaml
  external_components:
    - source:
      type: git
      url: https://github.com/PaulSchulz/esphome-lora-sc126x
      ref: main
    components: ["lora_sx126x"]
#+end_src

** Considerations / Things to fix
*** Direct use of SPI and SX126x-Arduino libraries
If possible, the SX126x-Arduino library needs to be implemented natively in
ESPHome, to make use of the native ESPHome SPI code.

It is uncertain at the moment whether this component can be used generally with
other devices that use the same SPI interface.

* Example YAML

Proposed example YAML configuration
#+begin_src yaml
  esphome:
    name: "lora-sx126x"
    libraries:
      - "SPI"
      - "Ticker"
      - "SX126x-Arduino"

  ...

  external_components:
    - source:
        type: local
        path: esphome/components

  ...

  lora_sx126x:
    sensor: name
#+end_src
