# This file is an example with a setup for using the SX126X LoRa radio chip.

esphome:
  name: "lora-sx126x"
  libraries:
     - "SPI"
     - "Ticker"
     - "SX126x-Arduino"

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

external_components:
  - source:
      type: local
      path: esphome/components 
    components: ["lora_sx126x"]

  - source:
      type: local
      path: ../esphome-heltec-battery/components
    components: ["empty_sensor"]
    
# Enable logging
logger:
  hardware_uart: "UART0"  # Heltec V3 boards
  
wifi:
  networks:
  - ssid: !secret wifi_ssid
    password: !secret wifi_password
  
ota:
  platform: esphome
  password: !secret ota_password

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

#
web_server:
  port: 80

#spi:i
#  clk_pin: GPIO9
#  mosi_pin: GPIO10s
#  miso_pin: GPIO11

#i2c:
#  - id: bus_a
#    sda: 17
#    scl: 18

#lora_sx126x:
#  name: "LoRa Radio"
#  # include LoRa radio configuration

#  lora_bandwidth:         1  # [0: 125 kHz, 1: 250 kHz, 2: 500 kHz, 3: Reserved]
#  lora_spreading_factor: 11  # [SF7..SF12]
#  lora_codingrate:        1  # [1: 4/5, 2: 4/6,  3: 4/7,  4: 4/8]
#  lora_preamble_length:   8  # same for Tx and Rx

sensor:
#  - platform: lora_sx126x
#    id: lorarssi
#    name: lorarssi                 # Required for publishing into API and HA 

  - platform: empty_sensor
    name: Empty Sensor

text_sensor:
  - platform: wifi_info
    ip_address:
      name: ESP IP Address
  - platform: version
    name: "ESPHome Version"
  - platform: template
    name: "Template Text Sensor"
    lambda: |-
      return {"Hello World"};
    update_interval: 60s
  - platform: lora_sx126x
    id: packet_in
    name: packet_in

binary_sensor:
  - platform: gpio
    pin: 5
    id: trigger
    name: "Trigger (In)"
    on_press:
      then:
        - switch.turn_on: monitor_switch    
    on_release:
      then:
        - switch.turn_off: monitor_switch

output:
  - platform: gpio
    pin: 6
    id: monitor
  - platform: gpio
    pin: 35
    id: monitor_led
    
switch:
  - platform: output
    id: monitor_switch
    name: "Monitor Output (Out)"
    output:
#     monitor
      monitor_led


